//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "access_groups")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub group_id: i32,
    pub group_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_groups::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_groups::Relation::AccessGroups.def().rev())
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::group_permissions::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::group_permissions::Relation::AccessGroups.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
