//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::access_groups::Entity as AccessGroups;
pub use super::group_permissions::Entity as GroupPermissions;
pub use super::otps::Entity as Otps;
pub use super::permissions::Entity as Permissions;
pub use super::user_groups::Entity as UserGroups;
pub use super::users::Entity as Users;
