//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub user_id: i32,
    pub username: String,
    pub password_hash: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::access_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_groups::Relation::AccessGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_groups::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
